config/routes.rb
Rails.application.routes.draw do

get '/bonjour(/:name)', to: 'pages#salut', as: 'salut'

root to: 'pages#home'

resources :charges, only: [:new, :create]

resources :posts


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
end

def create
  # Amount in cents
  @amount = 500

  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'eur'
  )

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def salut
    @name = params[:name]
  end

  def home

  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to posts_path
  end

  def new
    @post = Post.new
  end

  def create
    post =Post.create(post_params)
    redirect_to post_path(post.id)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:name, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/charges/create.html.erb
<div>
<h2>Mercie tu a payer <strong>€5.00</strong>!</h2>
</div>

app/views/charges/new.html.erb
<div>
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Paiment trop cool"
          data-amount="500"
          data-currency="eur"
          data-locale="auto"></script>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Supercite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
    crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>

  </head>

  <body>

      <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="<%= root_path %>"> Home </a>
        <ul class="nav navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="<%= salut_path %>">Salut </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/posts"> Articles </a>
          </li>
        </ul>
      </nav>

    <div class="container" style="padding-top: 5rem;">

      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>bien venue sur le site</h1>

<p>super agumenter de vante</p>

app/views/pages/salut.html.erb
<h1>bonjour les gent<h1>

  <p>salut <%= @name %> comment vas tu </p>

app/views/posts/edit.html.erb
<h1> Editer l'article </h1>

<%= form_for @post do |f| %>
  <div class="form-group">
    <label> Titre de l'article </label>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label> Contenu de l'article </label>
    <%= f.text_area :content, class: 'form-control' %>
  </div>
  <div class="form-group">
    <button type="submit"class="btn btn-primary">Modifier l'article </button>
  </div>
<% end %>

app/views/posts/index.html.erb
<h1>Aticles</h1>

<% @posts.each do |post| %>
    <h2> <%= post.name %> </h2>
    <p> <%= post.content %> </p>
    <p>
        <a href="<%= post_path(post.id) %>"class="btn btn-primary"> Lire la suite </a>
        <a href="<%= edit_post_path(post.id) %>"class="btn btn-default"> Editer </a>
        <a href="<%= post_path(post.id) %>"class="btn btn-danger" data-confirm="êtes vous sur ?"
          data-method="DELETE"> Supprimer </a>
    </p>
<% end %>

<p>
  <a href="<%= new_post_path %>" class="btn btn-success" > Créer un article </a>
</p>

app/views/posts/new.html.erb
<h1> Créer un article </h1>

<%= form_for @post do |f| %>
  <div class="form-group">
    <label> Titre de l'article </label>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label> Contenu de l'article </label>
    <%= f.text_area :content, class: 'form-control' %>
  </div>
  <div class="form-group">
    <button type="submit"class="btn btn-primary"> Céer l'article </button>
  </div>
<% end %>

app/views/posts/show.html.erb
<h1> <%= @post.name %> </h1>

<p> <%= @post.content %> </p>

<p>
  <a href="<%= posts_path %>" class="btn btn-primary">revenir au article</a>
</p>